<footer>
    <h2>Contact and Project Links</h2>

    <p>
        <a href="https://webtechteam.atlassian.net/jira/software/projects/WTP/boards/2?jql=assignee+IN+%28empty%2C+712020%3A0e8a7372-55e9-43e0-86dd-585e4fb9844a%29&amp%3BatlOrigin=eyJpIjoiZTg3ZTFkNzM0MDU2NDhmM2IwYTE0MmRmNzk1YTI4MDEiLCJwIjoiaiJ9&atlOrigin=eyJpIjoiMWM3ZmJmODBmYzg3NDYzZDgyNzI3ZjY5ODhiYjBiNWUiLCJwIjoiaiJ9"
        target="_blank"
        rel="noopener noreferrer">
        Jira Project Board
        </a>
    </p>

    <p>
        <a href="https://github.com/sazzad-hossain-shafin/Applied-Web-Project-Part-2.git"
        target="_blank"
        rel="noopener noreferrer">
        GitHub Repository
        </a>
    </p>

    <p>
        <a href="mailto:careers@greenleafenergy.com">
        careers@greenleafenergy.com
        </a>
    </p>

    <p>&copy; 2026 Green Leaf Energy. All rights reserved.</p>
</footer>

</body>
</html>